### ISSUE TITLE
When re-running experiments, any advice for hardware specs?

### ISSUE THREAD

**Issue by gabbifish** [ndal-eth/netbench#1]
I'm trying to re-run experiment 10_projector and am at the stage of editing the `deploy_10_projector.sh` script. I understand that we are supposed to provide credentials for multiple hosts, so each host can run netbench code as part of the simulation. Do you have recommended specs for VM instances that we would use as hosts? Or did you originally use your own bare-metal hardware for these simulations?

**Comment by snkas** [comment]
Ones with sufficient RAM and a decent CPU, as the simulation is CPU-bound.
I ran all experiments on ~20 single-tenant (i.e. "bare-metal") machines each with:

* CPU: Intel Xeon L5520 @ 2.26 GHz
* Core: 2x Quad core
* RAM: 24 GB
* ... running on a Linux OS with Java installed

The 10_projector experiments finish rather quickly if I remember correctly, because the number of involved nodes is rather small due to the extreme skewness of the workload.

**Comment by gabbifish** [comment]
Great--thanks for the quick response! I also wanted to check if 10_projector is the script that produces figures 10(a) and 10(c) from the paper. I'm also trying to replicate 11(a) and 11(c)--I'd greatly appreciate it if you could point me to the scripts that would replicate those results 😃

**Comment by snkas** [comment]
The naming of scripts is different from the numbering of the figures in the paper.

Figure 7(b/c): 1_failcases
Figure 8: 2_workload_summarization
Figure 9(a/b/c): 3_4_all_to_all_fraction/fig3
Figure 10(a/b/c): 5_6_pairings_fraction/fig5
Figure 11(a/b/c/): 9_oversub
Figure 12: 14_pareto_all_to_all
Figure 13(a/b/c): 10_projector
Figure 14 (a/b/c): 16_dual
Figure 15 (a/b/c): 17_duallarge

**Comment by gabbifish** [comment]
Thanks!!
